project_name: "x1biu"
default_status: "To Do"
statuses: ["To Do", "In Detailing", "Detailed", "In Architecting", "Architected", "In Execution", "Executed", "In Reviewing", "Reviewed", "In Documenting", "Done"]
labels: []
date_format: dd/mm/yyyy
max_column_width: 20
auto_open_browser: true
default_port: 6420
remote_operations: true
auto_commit: false
bypass_git_hooks: false
check_active_branches: true
active_branch_days: 30
task_prefix: "task"
