# Generated by Django 6.0.6 on 2026-06-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchparticipant',
            name='pitch_data',
            field=models.JSONField(default=list),
        ),
    ]
