# Generated by Django 6.0.6 on 2026-06-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='songs/'),
        ),
        migrations.AddField(
            model_name='song',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('ready', 'Pronto'), ('error', 'Erro')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='pitch_reference',
            field=models.JSONField(default=list),
        ),
    ]
